### PR TITLE
New DDB Algorithm with some Watermark cleanup

### PR DESCRIPTION
**Pull request by pallavigopal**

### CODE REVIEW

**Comment by pallavigopal** [comment]
@kalyankondapally @shobhitka  Please review

**Comment by kalyankondapally** [comment]
@Kishore409 sanity checking on joule

**Comment by tpalli** [comment]
are these backports from drm-tip?

**Comment by kalyankondapally** [comment]
ported from here tapani  https://patchwork.freedesktop.org/series/20152/

**Comment by kalyankondapally** [comment]
without this APL, BXT dont seem to work well

**Comment by pallavigopal** [comment]
I need to add some specific tag like from upstream to differentiate from the merged thing to the commit message. if there is any guideline like that please let me know

**Comment by kalyankondapally** [comment]
@pallavigopal Ya, you need to add FromList: as prefix to all commits

**Comment by tpalli** [comment]
I don't see all of these in drm-tip, better be careful and mark all patches that are in upstream from ones that have not been accepted.

**Comment by kalyankondapally** [comment]
Ya, there are not part of drm-tip tapani, still under review in mailing list but seem to pass all CI run upstream. @pallavigopal  Have FromList: as prefix, at the end add like cherrypicked from <patchwork link> and your signed off.

**Comment by Kishore409** [comment]
@kalyankondapally : The changes are validated and flickering is not seen as earlier and unable to find any regressions with Sanity

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
