### PR TITLE
hdmi_switch support

### PR DESCRIPTION
**Pull request by libinyang**
hdmi_switch support:
1. porting google's switch patches
2. enable hdmi audio switch support

### CODE REVIEW

**Comment by libinyang** [comment]
Summary of the patch:
This is a patch of enable hdmi_switch in kernel config.

Description of the fix.
The patches enable CONFIG_SWITCH, which will work with the below 3 patches to enable hdmi_switch:
aia: port switch class support  …			d24bc52
ALSA: hda - hdmi audio add support of switch  …			5cc8dea
config: enable CONFIG_SWITCH  …

Jira: (Link to Jira)
None

Test: (What tests are expected to pass).
With other 3 patches, it will enable hdmi_switch. There is "hdmi_state" node created in /sys/class/switch/pcixxxx/xxxx/  #xxxx is the pci id.

Signed-off-by:
Libin Yang <libin.yang@intel.com>

**Comment by kalyankondapally** [comment]
@libinyang can u check we still need this with our latest kernel update

**Comment by libinyang** [comment]
Hi Kalyan,

I’m currently ooo and I will check next week. I’m planning to use ext_con if possible for the hdmi switch.

Regards,
Libin

**Comment by kalyankondapally** [comment]
closing this for now. Please send in a new pull request with what is needed.

**Comment by libinyang** [comment]
Hi Kalyan,

These days I did some investigation on extcon. Sorry for delay, my develop machine is broken.

The conclusion is android doesn’t work with extcon well. So we still need switch class so far. My patches of HDMI switch are old and need update.

The details of investigation on extcon is:
The extcon Documents says it can work as switch class with basic functionality. But I found the extcon code are changed already and doesn’t match the document any more for the basic functionality. So I tried to work out patches to use the extcon extended multistate feature. This feature is powerful. However it doesn’t match android requirement.

Regards,
Libin

From: Yang, Libin
Sent: Wednesday, March 22, 2017 12:29 AM
To: android-ia/device-androidia-kernel <reply@reply.github.com>; android-ia/device-androidia-kernel <device-androidia-kernel@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [android-ia/device-androidia-kernel] hdmi_switch support (#4)

Hi Kalyan,

I’m currently ooo and I will check next week. I’m planning to use ext_con if possible for the hdmi switch.

Regards,
Libin

**Pull request closed without merging**
