### PR TITLE
AndroidIA: power_hal: Add sysfs based power_hal suspend support

### PR DESCRIPTION
**Pull request by kalyankondapally**
This patch implements the sysfs based PowerHAL interface that
deprecates early suspend support that has been removed.

Added a new sysfs group for power_hal suspend under
/sys/power/ directory. Every device that needs power_hal
suspend support needs to call following routines
to register/unregister power_hal suspend support.

register_power_hal_suspend_device():
Registers power_hal suspend support for the given device. Also,
Calling this routine will create a device specific symlink
under /sys/power/power_hal directory.

unregister_power_hal_suspend_device():
Unregisters power_hal suspend support for the given device. Also,
Calling this routine will remove a device specific symlink
under /sys/power/power_hal_suspend directory.

`ls /sys/power/power_hal/` from the userspace will give
us the list of devices that supports power_hal suspend functionality.

Signed-off-by: Sathyanarayanan Kuppuswamy <sathyanarayanan.kuppuswamy@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@eht25g  Please review

**Comment by kalyankondapally** [comment]
@eht25g Please review

**Comment by eht25g** [comment]
LGTM

**Comment by kalyankondapally** [comment]
thx merged

**Pull request closed without merging**
