### PR TITLE
PM / sleep: System sleep state selection interface rework

### PR DESCRIPTION
**Pull request by abhilashkesavan**
There are systems in which the platform doesn't support any special
sleep states, so suspend-to-idle (PM_SUSPEND_FREEZE) is the only
available system sleep state.  However, some user space frameworks
only use the "mem" and (sometimes) "standby" sleep state labels, so
the users of those systems need to modify user space in order to be
able to use system suspend at all and that may be a pain in practice.

Commit 0399d4db3edf (PM / sleep: Introduce command line argument for
sleep state enumeration) attempted to address this problem by adding
a command line argument to change the meaning of the "mem" string in
/sys/power/state to make it trigger suspend-to-idle (instead of
suspend-to-RAM).

However, there also are systems in which the platform does support
special sleep states, but suspend-to-idle is the preferred one anyway
(it even may save more energy than the platform-provided sleep states
in some cases) and the above commit doesn't help in those cases.

For this reason, rework the system sleep state selection interface
again (but preserve backwards compatibiliby).  Namely, add a new
sysfs file, /sys/power/mem_sleep, that will control the system
suspend mode triggered by writing "mem" to /sys/power/state (in
analogy with what /sys/power/disk does for hibernation).  Make it
select suspend-to-RAM ("deep" sleep) by default (if supported) and
fall back to suspend-to-idle ("s2idle") otherwise and add a new
command line argument, mem_sleep_default, allowing that default to
be overridden if need be.

At the same time, drop the relative_sleep_states command line
argument that doesn't make sense any more.

Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Tested-by: Mario Limonciello <mario.limonciello@dell.com>
(cherry picked from commit 406e79385f3223d82272cf2be86bc95cd000a258)
Signed-off-by: Abhilash Kesavan <abhilash.kesavan@intel.com>

### CODE REVIEW

**Comment by abhilashkesavan** [comment]
This is a back-ported upstream patch. Either this or https://github.com/android-ia/device-androidia-mixins/pull/44 will help enter s2idle on Joule. Please review and pick one of them.

**Comment by kalyankondapally** [comment]
Add UPSTREAM prefix so we know this is from upstream kernel, also add Jira, tests etc

**Comment by kalyankondapally** [comment]
LGTM

**Comment by Kishore409** [comment]
@abhilashkesavan @kalyankondapally , the patch is sanity tested

**Comment by Kishore409** [comment]
Merged, Thanks

**Pull request merged**
